name: tc-track-analogues
channels:
  - conda-forge
  - defaults
dependencies:
  - python
  - numpy
  - pandas
  - xarray
  - matplotlib
  - cartopy
  - seaborn
  - cmcrameri
  - scipy
  - haversine
  - tqdm
  - huracanpy
  - datetime
  - pip
  - pip:
    - -e .

# Update active conda environment with this file
# conda env update --file environment.yml --prune